apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-gsuq
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0049-tenant/tkrw-pr712-0075-0049-app/devfile-sample-gsuq@sha256:a5ce1ce4717e3c495199d331b3697182ea7f82a0dbb3bcc296bb264d3c152d52
        name: my-nodejs
        resources: {}
status: {}
